/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development environments.
// It is committed here so the repository type-checks consistently from day one.
